"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a385ab)\
[  ](bg:#a385ab fg:#090c0c)\
[](bg:#6e5375 fg:#a385ab)\
$directory\
[](fg:#6e5375 bg:#4d3b52)\
$git_branch\
$git_status\
[](fg:#4d3b52 bg:#3c2e40)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#3c2e40 bg:#362b38)\
$time\
[ ](fg:#362b38)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#6e5375"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#4d3b52"
format = '[[ $symbol $branch ](fg:#ecaefc bg:#4d3b52)]($style)'

[git_status]
style = "bg:#4d3b52"
format = '[[($all_status$ahead_behind )](fg:#ecaefc bg:#4d3b52)]($style)'

[nodejs]
symbol = ""
style = "bg:#3c2e40"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#3c2e40)]($style)'

[rust]
symbol = ""
style = "bg:#3c2e40"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#3c2e40)]($style)'

[golang]
symbol = ""
style = "bg:#3c2e40"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#3c2e40)]($style)'

[php]
symbol = ""
style = "bg:#3c2e40"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#3c2e40)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#362b38"
format = '[[  $time ](fg:#f1c5fc bg:#362b38)]($style)'
